/** Error codes and their HTTP status mapping — canonical source: FRS Section 14 (Error Catalogue). */

export const ERROR_CODES = {
  // 14.1 Authentication Errors
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',

  // 14.2 Password Reset Errors
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  PASSWORD_SAME_AS_CURRENT: 'PASSWORD_SAME_AS_CURRENT',
  OTP_RATE_LIMIT: 'OTP_RATE_LIMIT',
  OTP_VERIFY_RATE_LIMIT: 'OTP_VERIFY_RATE_LIMIT',

  // 14.3 Notes Errors
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  ALREADY_DELETED: 'ALREADY_DELETED',
  NOT_DELETED: 'NOT_DELETED',
  RECOVERY_EXPIRED: 'RECOVERY_EXPIRED',
  CONTENT_TOO_LARGE: 'CONTENT_TOO_LARGE',

  // 14.4 Tags Errors
  TAG_NAME_EXISTS: 'TAG_NAME_EXISTS',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',

  // 14.5 Sharing Errors
  SHARE_LINK_EXPIRED: 'SHARE_LINK_EXPIRED',
  SHARE_LINK_NOT_FOUND: 'SHARE_LINK_NOT_FOUND',

  // 14.6 Version History Errors
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',

  // 14.7 General Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  EMAIL_ALREADY_EXISTS: 409,
  INVALID_CREDENTIALS: 401,
  TOKEN_MISSING: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  INVALID_REFRESH_TOKEN: 401,
  REFRESH_TOKEN_EXPIRED: 401,

  INVALID_OTP: 401,
  OTP_EXPIRED: 410,
  INVALID_RESET_TOKEN: 401,
  RESET_TOKEN_EXPIRED: 410,
  PASSWORD_SAME_AS_CURRENT: 422,
  OTP_RATE_LIMIT: 429,
  OTP_VERIFY_RATE_LIMIT: 429,

  NOTE_NOT_FOUND: 404,
  ALREADY_DELETED: 409,
  NOT_DELETED: 409,
  RECOVERY_EXPIRED: 410,
  CONTENT_TOO_LARGE: 413,

  TAG_NAME_EXISTS: 409,
  TAG_NOT_FOUND: 404,

  SHARE_LINK_EXPIRED: 410,
  SHARE_LINK_NOT_FOUND: 404,

  VERSION_NOT_FOUND: 404,

  VALIDATION_ERROR: 422,
  RATE_LIMIT_EXCEEDED: 429,
  INTERNAL_ERROR: 500,
  METHOD_NOT_ALLOWED: 405,
  ROUTE_NOT_FOUND: 404,
};
